"""create_permissions_table

Revision ID: ab334ca26fda
Revises: 9480ceba4459
Create Date: 2026-02-02 14:38:32.330287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab334ca26fda'
down_revision: Union[str, None] = '9480ceba4459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_permissions_code'), 'permissions', ['code'], unique=True, schema='public')
    op.create_index(op.f('ix_public_permissions_id'), 'permissions', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_permissions_name'), 'permissions', ['name'], unique=True, schema='public')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_status_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'users', 'statuses', ['status_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_status_id_fkey', 'users', 'statuses', ['status_id'], ['id'])
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_public_permissions_name'), table_name='permissions', schema='public')
    op.drop_index(op.f('ix_public_permissions_id'), table_name='permissions', schema='public')
    op.drop_index(op.f('ix_public_permissions_code'), table_name='permissions', schema='public')
    op.drop_table('permissions', schema='public')
    # ### end Alembic commands ###
