"""create_roles_table

Revision ID: b1a0cef6c9d6
Revises: e9d6127d31e6
Create Date: 2026-02-02 14:13:46.413957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a0cef6c9d6'
down_revision: Union[str, None] = 'e9d6127d31e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_roles_code'), 'roles', ['code'], unique=True, schema='public')
    op.create_index(op.f('ix_public_roles_id'), 'roles', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_roles_name'), 'roles', ['name'], unique=True, schema='public')
    op.drop_constraint('users_status_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'users', 'statuses', ['status_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_status_id_fkey', 'users', 'statuses', ['status_id'], ['id'])
    op.drop_index(op.f('ix_public_roles_name'), table_name='roles', schema='public')
    op.drop_index(op.f('ix_public_roles_id'), table_name='roles', schema='public')
    op.drop_index(op.f('ix_public_roles_code'), table_name='roles', schema='public')
    op.drop_table('roles', schema='public')
    # ### end Alembic commands ###
