"""create_role_permissions_table

Revision ID: c63f7fc627a9
Revises: 70293497be25
Create Date: 2026-02-02 14:51:19.964719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63f7fc627a9'
down_revision: Union[str, None] = '70293497be25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['public.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions', schema='public')
    # ### end Alembic commands ###
