"""create_statuses_table

Revision ID: d8a51b5681c3
Revises: 
Create Date: 2026-02-02 13:35:00.832148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8a51b5681c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_statuses_id'), 'statuses', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_statuses_name'), 'statuses', ['name'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_statuses_name'), table_name='statuses', schema='public')
    op.drop_index(op.f('ix_public_statuses_id'), table_name='statuses', schema='public')
    op.drop_table('statuses', schema='public')
    # ### end Alembic commands ###
